name: Licensed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-licensed:
    name: Licensed
    uses: HarithaVattikuti/reusable-workflows/.github/workflows/licensed.yml@testrw
